### ISSUE TITLE
Static Assets

### ISSUE THREAD

**Issue by evanleck** [ohler55/agoo#24]
Sorry to bother you again, but I have a question about static assets. The docs say that the root passed to `Agoo::Server.init` is for static assets but it seems like there's more required to serve static assets than that.

I have compiled CSS and JS in `public/assets` and a robots.txt file at `public/robots.txt`. Initializing Agoo with `Agoo::Server.init(3000, 'public')` doesn't serve any of the static files in `public`. Adding `Agoo::Server.path_group('/assets', ['public/assets'])` gets Agoo serving all of the files from `public/assets` but I can't figure out how to get `public/robots.txt` served by Agoo. Any ideas?

What's the root passed into `init` actually do?

Thanks!

**Comment by ohler55** [comment]
It does get tricky. Rack and rails want to own the de-multiplexing so the concepts are a bit new. I’ll write up a discussion of how to get it working tonight. 

Thank you for gaining Agoo a try. It help me to improve it based on your feedback.

**Comment by evanleck** [comment]
That'd be great, thank you! And thanks for being so responsive!

**Comment by ohler55** [comment]
Pushed a doc in `misc/optimize.md` that may help.

Looking at your issue I wonder how you are running Agoo. I suspect not Rack or Rails so you should turn on checking the root first before attempting the Ruby handler. `-root_first`.

**Comment by evanleck** [comment]
Cool, thanks for adding that!

I tried configuring Agoo with `Agoo::Server.init(3000, 'public', root_first: true)` where all of my static assets are under the "public" directory and it crashes on the first request for a static asset with the message `fish: 'ruby server.rb' terminated by signal SIGABRT (Abort)`.

Adding `Agoo::Server.path_group('/assets', ['public/assets'])` prevents it from crashing for assets in "public/assets" but it crashes with the same message when I try to load "/robots.txt". Without `root_first: true`, however, the request for "/robots.txt" just returns a 404 and is handled by my Rack application.

Maybe something weird is happening with `root_first: true`? Can I get you more info somehow? I have all of the logging turned on, but I don't see anything besides the crash message in the terminal.

**Comment by ohler55** [comment]
That is a truly off error message. I'm not sure where the `fish` comes from. Do you have a simple version of the app I can try? Are you on maxOS or Linux?

**Comment by evanleck** [comment]
In my case, `fish` is the shell I'm running in but it fails just the same in `zsh` and `bash`, though bash also returned the message "Abort trap: 6".

I set up a minimal test repository here https://github.com/evanleck/agoo-root-first-test that you can try out. Hitting any path like "/" works fine, but "/robots.txt" crashes the server. I'm running macOS 10.13.5.

**Comment by ohler55** [comment]
Super, thanks. It looks almost the same as my example test. I'll dig into it tonight.

**Comment by ohler55** [comment]
I updated you example with a PR. It worked for me on Ubuntu as expected. I'll test a Mac next. I'm not giving up until we get it figured out.

**Comment by ohler55** [comment]
Mac worked okay as well but I am one behind at macOS 10.3.4. I'll upgrade and try again.

**Comment by evanleck** [comment]
If it matters, I'm running Ruby version `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`.

**Comment by ohler55** [comment]
Same here.

**Comment by ohler55** [comment]
Does any other file in / cause an abort or just robots.txt?

**Comment by evanleck** [comment]
Yeah, I just added a test CSS file and it aborts loading that as well:

```
➜  agoo-test git:(master) ✗ ruby --debug -I ~/Clones/agoo/ext -I ~/Clones/agoo/lib server.rb 
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1406 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1415 - cannot load such file -- rubygems/defaults/ruby
/Users/evan/Clones/agoo/lib/rack/handler/agoo.rb:59: warning: shadowing outer local variable - handler
/Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59: warning: loading in progress, circular require considered harmful - /Users/evan/Clones/agoo/lib/agoo.rb
	from server.rb:1:in  `<main>'
	from /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in  `require'
	from /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in  `require'
	from /Users/evan/Clones/agoo/lib/agoo.rb:6:in  `<top (required)>'
	from /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in  `require'
	from /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in  `require'
	from /Users/evan/Clones/agoo/lib/rack/handler/agoo.rb:2:in  `<top (required)>'
	from /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in  `require'
	from /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in  `require'
Exception `NoMethodError' at /Users/evan/Clones/agoo/lib/rack/handler/agoo.rb:84 - undefined method `register' for Rack::Handler:Module
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59 - cannot load such file -- agoo/agoo
I 2018/06/04 15:33:43.078148000 INFO: Agoo 2.2.2 with pid 43589 is listening on port 3000.
I 2018/06/04 15:33:53.140944000 connect: Server with pid 43589 accepted connection 1 on port 3000 [17]
I 2018/06/04 15:33:53.142609000 request: 1: GET /other.css HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: __boring__
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
fish: 'ruby --debug -I ~/Clones/agoo/e…' terminated by signal SIGABRT (Abort)
```

**Comment by ohler55** [comment]
Interesting errors. Lets me try here.

**Comment by ohler55** [comment]
I fixed two of the warnings. Don't think it will make a difference though. Pushed to the develop branch.

**Comment by ohler55** [comment]
I don't see the error about loading agoo/agoo on my setup. I wonder if that is related to the issue.

**Comment by evanleck** [comment]
Hmm, I wonder. It would appear to come from `lib/agoo.rb`, right?

I just tried it again with latest from the develop branch and I get different errors on boot, but it still crashes:

```
➜  agoo-test git:(master) ruby --debug -I ~/Clones/agoo/ext -I ~/Clones/agoo/lib server.rb 
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1406 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1415 - cannot load such file -- rubygems/defaults/ruby
Exception `NoMethodError' at /Users/evan/Clones/agoo/lib/rack/handler/agoo.rb:84 - undefined method `register' for Rack::Handler:Module
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59 - cannot load such file -- agoo/agoo
I 2018/06/04 16:00:08.672141000 INFO: Agoo 2.2.2 with pid 45809 is listening on port 3000.
I 2018/06/04 16:00:11.351976000 connect: Server with pid 45809 accepted connection 1 on port 3000 [17]
I 2018/06/04 16:00:11.352516000 request: 1: GET /robots.txt HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: __boring__
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
If-Modified-Since: Thu, 31 May 2018 21:49:38 GMT
Cache-Control: max-age=0
fish: 'ruby --debug -I ~/Clones/agoo/e…' terminated by signal SIGABRT (Abort)
```

**Comment by ohler55** [comment]
Can you try this, do a gem uninstall agoo to make sure an older version is not getting in the way. The use the develop branch.

**Comment by ohler55** [comment]
I only see 3 exceptions here. There should not be a LoadError. That may be the key.

**Comment by evanleck** [comment]
Alright, I uninstalled all versions of the gem using `gem uninstall agoo` and added a `gems.rb` file pointing to the develop branch. It still crashes :/

```
➜  agoo-test git:(master) ✗ ruby --debug server.rb 
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1406 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1415 - cannot load such file -- rubygems/defaults/ruby
Exception `NameError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:590 - method `gem' not defined in #<Class:Kernel>
Exception `NoMethodError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/agoo-c2fe20e03008/lib/rack/handler/agoo.rb:84 - undefined method `register' for Rack::Handler:Module
I 2018/06/04 16:11:55.709030000 INFO: Agoo 2.2.2 with pid 48198 is listening on port 3000.
I 2018/06/04 16:11:57.199805000 connect: Server with pid 48198 accepted connection 1 on port 3000 [19]
I 2018/06/04 16:11:57.199903000 request: 1: GET /robots.txt HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
If-Modified-Since: Thu, 31 May 2018 21:49:38 GMT
Cache-Control: max-age=0
fish: 'ruby --debug server.rb' terminated by signal SIGABRT (Abort)
```

**Comment by ohler55** [comment]
Well, the load error for agoo/agoo is gone but it clearly didn't change anything.

I have another machine at work I can try. Maybe I can duplicate it there. The next step after that, if you are willing is for me to make a branch that has a bunch of print statements in it to see if we can narrow down the location of where this is happening. Are you willing or is it too much effort on your part?

**Comment by evanleck** [comment]
I'm absolutely willing to help debug, I appreciate you taking so much time to help figure out what's going on!

**Comment by ohler55** [comment]
Funny, I do see some additional headers in your that my Firefox, also version 60.0 does not emit.
```
I 2018/06/04 19:32:33.649164000 request: 1: GET /robots.txt HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: keep-alive
Upgrade-Insecure-Requests: 1
```

**Comment by ohler55** [comment]
okay, let me try another machine tomorrow and then see what else we can try after that. Thanks.

**Comment by evanleck** [comment]
Yeah, I just tried with Safari and it actually worked! I wonder if Firefox is doing something unexpected...

**Comment by evanleck** [comment]
Though Safari worked for a minute, trying a new request from Firefox still crashes the server.

**Comment by ohler55** [comment]
Even if it it works with Safari Agoo should not abort with Firefox.

**Comment by ohler55** [comment]
Looks like it is going to have to be the hard way. Test worked on the other machine as well with Firefox. I also ran a test that passed in the same header as what you provided and it worked fine. Next step is lots of print statements.

**Comment by ohler55** [comment]
`trace` branch has some print statements. Please try. It may take a few iterations to narrow it down.

**Comment by evanleck** [comment]
Cool, I just updated my test repository to point to that.

I just noticed that opening /robots.txt in a new private browsing window (still Firefox) works fine. In my normal browser, however, it still fails. Here's the output from the normal window:

```
➜  agoo-test git:(master) ✗ ruby --debug server.rb 
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1406 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1415 - cannot load such file -- rubygems/defaults/ruby
Exception `NameError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:590 - method `gem' not defined in #<Class:Kernel>
Exception `NoMethodError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/agoo-90e380e4e9aa/lib/rack/handler/agoo.rb:84 - undefined method `register' for Rack::Handler:Module
I 2018/06/05 10:02:35.271975000 INFO: Agoo 2.2.2 with pid 61650 is listening on port 3000.
I 2018/06/05 10:02:41.613743000 connect: Server with pid 61650 accepted connection 1 on port 3000 [19]
I 2018/06/05 10:02:41.614249000 request: 1: GET /robots.txt HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Cookie: authenticity_token_a4569815bc13=49f47502b1624514151e3fa2858ed4c7964719a27ff68be9d421278e12964781; tracking_id=1ece70bbcfd4520ff4e26ffa28bf971431660669db2e4822a8b7223e3e23e7c8; marketing_id=982713793433063; hblid=BIq7GbqPbIxMGX5M9r7Jz0X0D1uAAy20; olfsk=olfsk45532810509565214; _ga=GA1.1.331047845.1511077615; __distillery=b396261_66318f7f-05ec-4e9d-b6d1-e8ec645d3b6c-2029e1d49-6cb782395c87-10d0; app_a4569815bc13=51eeed18b733cbd84ce0404da57c1e3cf2bcc12332b2dc85e8b3319300d3b75b; muxData=mux_viewer_id=74f81afe-5909-4e01-b662-e8202e859388&msn=0.3985026743779515; superHSession=6fd24ec6-b0a0-460a-8d21-48e58c0d4263; harmony_session=181527080a36ee2917c59ad718a64fe8684a0f6b2c924ee40690f8cb561dff01bb0cbb04b972fd6259db48b650fcddbb32b225f181d87f5f6a3f9fc5eebabf41; ASP.NET_SessionId=uoehwkumd3eotrotq5mrkyw1; wcsid=TXpBxHQckO0K7U0V9r7Jz0W01FADoA20; _oklv=1525107807462%2CTXpBxHQckO0K7U0V9r7Jz0W01FADoA20; _okdetect=%7B%22token%22%3A%2215224426854560%22%2C%22proto%22%3A%22http%3A%22%2C%22host%22%3A%22localhost%3A3000%22%7D
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0
*** before GET with root_first: 1
*** page_get
*** page_get path /robots.txt
*** before update contents for /robots.txt
*** update contents for public/robots.txt
*** update contents for public/robots.txt after stats
*** update contents for public/robots.txt before read
*** update contents for public/robots.txt after read
*** after update contents for /robots.txt
fish: 'ruby --debug server.rb' terminated by signal SIGABRT (Abort)
```

And here's the output from the private browsing window:

```
➜  agoo-test git:(master) ruby --debug server.rb 
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1406 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1415 - cannot load such file -- rubygems/defaults/ruby
Exception `NameError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/bundler/rubygems_integration.rb:590 - method `gem' not defined in #<Class:Kernel>
Exception `NoMethodError' at /Users/evan/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/bundler/gems/agoo-90e380e4e9aa/lib/rack/handler/agoo.rb:84 - undefined method `register' for Rack::Handler:Module
I 2018/06/05 10:04:33.994071000 INFO: Agoo 2.2.2 with pid 61797 is listening on port 3000.
I 2018/06/05 10:04:37.075575000 connect: Server with pid 61797 accepted connection 1 on port 3000 [19]
I 2018/06/05 10:04:37.075931000 request: 1: GET /robots.txt HTTP/1.1
Host: localhost:3000
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Upgrade-Insecure-Requests: 1
*** before GET with root_first: 1
*** page_get
*** page_get path /robots.txt
*** before update contents for /robots.txt
*** update contents for public/robots.txt
*** update contents for public/robots.txt after stats
*** update contents for public/robots.txt before read
*** update contents for public/robots.txt after read
*** after update contents for /robots.txt
*** found the page, returning -346
*** con_http_write
I 2018/06/05 10:04:37.076228000 response: 1: HTTP/1.1 200 OK
Content-Type: text/plain
Content-Length: 7
I 2018/06/05 10:04:42.630740000 connect: Connection 1 closed.
```

The biggest difference that I see is the `Cookie` HTTP header. I've been redacting those thus far because my cookies in Firefox were pretty long so it was distracting, but I wonder if that has something to do with the error? I've included them with the first example.

**Comment by ohler55** [comment]
Score! It is the cookie. I'll get that fixed. Thanks. That was a big help.

**Comment by evanleck** [comment]
Woo! That's awesome!

**Comment by ohler55** [comment]
ok, pushed a fix in the trace branch.

**Comment by evanleck** [comment]
Works like a charm!

**Comment by ohler55** [comment]
Excellent. Will release tonight.

**Comment by evanleck** [comment]
Looks great with the 2.2.2 release, thanks again!

**Comment by ohler55** [comment]
Glad you stayed with me till I figured it out. Thanks. Hope you fine Agoo to be fast and what you are looking for.
